-- AlterTable
ALTER TABLE `users` ADD COLUMN `birth_date` DATE NULL,
ADD COLUMN `phone` VARCHAR(20) NULL,
ADD COLUMN `bio` TEXT NULL,
ADD COLUMN `website` VARCHAR(255) NULL,
ADD COLUMN `address` VARCHAR(255) NULL,
ADD COLUMN `city` VARCHAR(100) NULL,
ADD COLUMN `postal_code` VARCHAR(10) NULL,
ADD COLUMN `country` VARCHAR(100) NULL DEFAULT 'France',
ADD COLUMN `experience_years` INT NULL,
ADD COLUMN `social_media` JSON NULL,
ADD COLUMN `specialties` JSON NULL,
ADD COLUMN `languages` JSON NULL;

