import prisma from '../prisma.js';

export const LocationType = {
  PRESTATAIRE_LOCATION_TYPE_ID: 1,
  STORY_LOCATION_TYPE_ID: 2,
  OTHER_LOCATION_TYPE_ID: 3,
};

interface LocationSeed {
  id_location: number;
  name: string;
  description?: string;
  static_code?: string;
  price: number;
  purchased: boolean;
  position: [number, number];
  icon_name?: string;
  banner_name?: string;
  id_location_type: number;
  id_prestataire?: number | null;
}

const LOCATION_SEEDS: LocationSeed[] = [
  // === Main Quest Locations ===
  {
    id_location: 1,
    static_code: 'TICKET_OFFICE',
    name: "The Ticket Office",
    description:
      'A quaint wooden building adorned with colorful banners. The ticket officer, a jovial man named Garin, sells tickets to adventurers eager to explore the realm.',
    price: 0,
    purchased: true,
    id_location_type: LocationType.STORY_LOCATION_TYPE_ID,
    position: [1747, 5072],
    icon_name: 'ticketOffice',
    banner_name: 'images/locations/biletterie.png',
  },
  {
    id_location: 2,
    static_code: 'WITCH_HUT',
    name: "The Witch's Hut",
    description:
      'A mysterious dwelling shrouded in purple mist. The witch Morgana crafts powerful potions and enchantments for those brave enough to seek her services.',
    price: 0,
    purchased: true,
    id_location_type: LocationType.STORY_LOCATION_TYPE_ID,
    position: [910, 4330],
    icon_name: 'witchHouse',
    banner_name: 'images/locations/sorcerer.png',
  },
  {
    id_location: 3,
    static_code: 'SAGE_HOUSE',
    name: "The Great Sage's House",
    description:
      'A towering library filled with ancient tomes and scrolls. The sage Eldric shares wisdom and teaches powerful spells to worthy students.',
    price: 0,
    purchased: true,
    id_location_type: LocationType.STORY_LOCATION_TYPE_ID,
    position: [1344, 3572],
    icon_name: 'sage',
    banner_name: 'images/locations/great_sage.jpg',
  },
  {
    id_location: 4,
    static_code: 'INFORMATION_CENTER',
    name: 'The Information Center',
    description:
      'A bustling hub where adventurers gather to share news and seek guidance. The center is run by a knowledgeable clerk who provides maps and quest details.',
    price: 0,
    purchased: true,
    id_location_type: LocationType.STORY_LOCATION_TYPE_ID,
    position: [1580, 4488],
    icon_name: 'informationCenter',
    banner_name: 'images/medieval_image.jpg',
  },
  {
    id_location: 5,
    static_code: 'ROYAL_CASTLE',
    name: 'The Royal Castle',
    description:
      'The magnificent seat of power in the kingdom. The castle houses the royal family and serves as the center of governance and justice.',
    price: 0,
    purchased: true,
    id_location_type: LocationType.STORY_LOCATION_TYPE_ID,
    position: [2856, 3770],
    icon_name: 'castle',
    banner_name: 'images/medieval_image.jpg',
  },
  {
    id_location: 6,
    static_code: 'TRAINING_CAMP',
    name: 'The Training Camp',
    description:
      'A rugged encampment where warriors hone their combat skills. The camp is led by a grizzled veteran who trains recruits in the art of battle.',
    price: 0,
    purchased: true,
    id_location_type: LocationType.STORY_LOCATION_TYPE_ID,
    position: [1352, 2678],
    icon_name: 'trainingCamp',
    banner_name: 'images/locations/training_camp.jpg',
  },
  {
    id_location: 7,
    static_code: 'ARCHERY_RANGE',
    name: 'The Archery range',
    description:
      'A peaceful range where archers practice their marksmanship. The range is overseen by a skilled archer who offers lessons to aspiring bowmen.',
    price: 0,
    purchased: true,
    id_location_type: LocationType.STORY_LOCATION_TYPE_ID,
    position: [1528, 3304],
    icon_name: 'archeryRange',
    banner_name: 'images/locations/training_camp.jpg',
  },
  {
    id_location: 8,
    static_code: 'VILLAGE_FOOL',
    name: 'The Village Fool',
    description:
      'A villager known for his antics and humorous tales. Despite his foolish demeanor, he often provides unexpected insights.',
    price: 0,
    purchased: true,
    id_location_type: LocationType.STORY_LOCATION_TYPE_ID,
    position: [2556, 4647],
    icon_name: 'villageFool',
    banner_name: 'images/locations/training_camp.jpg',
  },
  {
    id_location: 9,
    static_code: 'CHILD',
    name: 'The Child',
    description:
      'A curious child who dreams of becoming a great adventurer one day. He often asks questions about the world beyond the village.',
    price: 0,
    purchased: true,
    id_location_type: LocationType.STORY_LOCATION_TYPE_ID,
    position: [1008, 2165],
    icon_name: 'child',
    banner_name: 'images/medieval_image.jpg',
  },
  {
    id_location: 10,
    static_code: 'FARMER',
    name: 'The Farmer',
    description:
      'A hardworking farmer who tends to the village fields. He provides food and supplies to adventurers passing through.',
    price: 0,
    purchased: true,
    id_location_type: LocationType.STORY_LOCATION_TYPE_ID,
    position: [2060, 1728],
    icon_name: 'farmer',
    banner_name: 'images/medieval_image.jpg',
  },
  {
    id_location: 11,
    static_code: 'LUMBERJACK',
    name: 'The Lumberjack',
    description:
      'A burly lumberjack who harvests wood from the nearby forest. He is known for his strength and skill with an axe.',
    price: 0,
    purchased: true,
    id_location_type: LocationType.STORY_LOCATION_TYPE_ID,
    position: [3040, 2724],
    icon_name: 'lumberjack',
    banner_name: 'images/medieval_image.jpg',
  },

  // === Prestataire / Buyable Locations (without owner) ===
  {
    id_location: 14,
    static_code: 'PRESTA_STALL_5',
    name: 'Merchant Stall #5',
    description:
      'A popular location among travelers, known for its high foot traffic.',
    price: 140,
    purchased: false,
    id_prestataire: null,
    id_location_type: LocationType.PRESTATAIRE_LOCATION_TYPE_ID,
    position: [2254, 1897],
    icon_name: 'prestataire',
    banner_name: 'images/locations/buyable.png',
  },
  {
    id_location: 15,
    static_code: 'PRESTA_STALL_6',
    name: 'Merchant Stall #6',
    description:
      'Situated near the town square, this stall benefits from constant visibility.',
    price: 160,
    purchased: false,
    id_prestataire: null,
    id_location_type: LocationType.PRESTATAIRE_LOCATION_TYPE_ID,
    position: [2188, 2139],
    icon_name: 'prestataire',
    banner_name: 'images/locations/buyable.png',
  },
  {
    id_location: 16,
    static_code: 'PRESTA_STALL_7',
    name: 'Merchant Stall #7',
    description:
      'A strategic location for merchants, close to the main road.',
    price: 110,
    purchased: false,
    id_prestataire: null,
    id_location_type: LocationType.PRESTATAIRE_LOCATION_TYPE_ID,
    position: [2006, 2383],
    icon_name: 'prestataire',
    banner_name: 'images/locations/buyable.png',
  },
  {
    id_location: 17,
    static_code: 'PRESTA_STALL_8',
    name: 'Merchant Stall #8',
    description:
      'A cozy stall, perfect for selling handmade goods and local crafts.',
    price: 115,
    purchased: false,
    id_prestataire: null,
    id_location_type: LocationType.PRESTATAIRE_LOCATION_TYPE_ID,
    position: [2386, 3379],
    icon_name: 'prestataire',
    banner_name: 'images/locations/buyable.png',
  },
  {
    id_location: 18,
    static_code: 'PRESTA_STALL_9',
    name: 'Merchant Stall #9',
    description:
      'Known for its vibrant atmosphere and diverse range of products.',
    price: 125,
    purchased: false,
    id_prestataire: null,
    id_location_type: LocationType.PRESTATAIRE_LOCATION_TYPE_ID,
    position: [2236, 2491],
    icon_name: 'prestataire',
    banner_name: 'images/locations/buyable.png',
  },
  {
    id_location: 19,
    static_code: 'PRESTA_STALL_10',
    name: 'Merchant Stall #10',
    description:
      'A prime spot for attracting both locals and tourists alike.',
    price: 135,
    purchased: false,
    id_prestataire: null,
    id_location_type: LocationType.PRESTATAIRE_LOCATION_TYPE_ID,
    position: [2346, 2271],
    icon_name: 'prestataire',
    banner_name: 'images/locations/buyable.png',
  },
  {
    id_location: 20,
    static_code: 'PRESTA_STALL_11',
    name: 'Merchant Stall #11',
    description:
      'Located at a busy intersection, ensuring a steady stream of potential customers.',
    price: 145,
    purchased: false,
    id_prestataire: null,
    id_location_type: LocationType.PRESTATAIRE_LOCATION_TYPE_ID,
    position: [2142, 2949],
    icon_name: 'prestataire',
    banner_name: 'images/locations/buyable.png',
  },
  {
    id_location: 21,
    static_code: 'PRESTA_STALL_12',
    name: 'Merchant Stall #12',
    description:
      'A bustling area known for its lively market scene and diverse offerings.',
    price: 155,
    purchased: false,
    id_prestataire: null,
    id_location_type: LocationType.PRESTATAIRE_LOCATION_TYPE_ID,
    position: [1946, 3171],
    icon_name: 'prestataire',
    banner_name: 'images/locations/buyable.png',
  },
  {
    id_location: 22,
    static_code: 'PRESTA_STALL_13',
    name: 'Merchant Stall #13',
    description:
      'Close to the tavern, this stall benefits from thirsty travelers looking for refreshments.',
    price: 165,
    purchased: false,
    id_prestataire: null,
    id_location_type: LocationType.PRESTATAIRE_LOCATION_TYPE_ID,
    position: [2398, 2599],
    icon_name: 'prestataire',
    banner_name: 'images/locations/buyable.png',
  },
  {
    id_location: 23,
    static_code: 'PRESTA_STALL_14',
    name: 'Merchant Stall #14',
    description:
      'A favored spot for its proximity to the stables and the smell of fresh hay.',
    price: 175,
    purchased: false,
    id_prestataire: null,
    id_location_type: LocationType.PRESTATAIRE_LOCATION_TYPE_ID,
    position: [2556, 2025],
    icon_name: 'prestataire',
    banner_name: 'images/locations/buyable.png',
  },
  {
    id_location: 24,
    static_code: 'PRESTA_STALL_15',
    name: 'Merchant Stall #15',
    description:
      'Known for its excellent view of the market square, ideal for attracting attention.',
    price: 185,
    purchased: false,
    id_prestataire: null,
    id_location_type: LocationType.PRESTATAIRE_LOCATION_TYPE_ID,
    position: [2616, 2273],
    icon_name: 'prestataire',
    banner_name: 'images/locations/buyable.png',
  },
  {
    id_location: 25,
    static_code: 'PRESTA_STALL_16',
    name: 'Merchant Stall #16',
    description:
      'A strategic location near the fountain, popular with both locals and tourists.',
    price: 195,
    purchased: false,
    id_prestataire: null,
    id_location_type: LocationType.PRESTATAIRE_LOCATION_TYPE_ID,
    position: [2426, 1671],
    icon_name: 'prestataire',
    banner_name: 'images/locations/buyable.png',
  },
  {
    id_location: 26,
    static_code: 'PRESTA_STALL_17',
    name: 'Merchant Stall #17',
    description:
      'Close to the entrance of the market, ensuring high visibility for your goods.',
    price: 205,
    purchased: false,
    id_prestataire: null,
    id_location_type: LocationType.PRESTATAIRE_LOCATION_TYPE_ID,
    position: [2324, 1517],
    icon_name: 'prestataire',
    banner_name: 'images/locations/buyable.png',
  },
  {
    id_location: 27,
    static_code: 'PRESTA_STALL_18',
    name: 'Merchant Stall #18',
    description:
      'A charming stall with a great view of the castle, perfect for attracting tourists.',
    price: 215,
    purchased: false,
    id_prestataire: null,
    id_location_type: LocationType.PRESTATAIRE_LOCATION_TYPE_ID,
    position: [2266, 1404],
    icon_name: 'prestataire',
    banner_name: 'images/locations/buyable.png',
  },
  {
    id_location: 28,
    static_code: 'PRESTA_STALL_19',
    name: 'Merchant Stall #19',
    description:
      "Located near the bard's stage, enjoy the added benefit of musical entertainment.",
    price: 225,
    purchased: false,
    id_prestataire: null,
    id_location_type: LocationType.PRESTATAIRE_LOCATION_TYPE_ID,
    position: [2226, 1295],
    icon_name: 'prestataire',
    banner_name: 'images/locations/buyable.png',
  },
  {
    id_location: 29,
    static_code: 'PRESTA_STALL_20',
    name: 'Merchant Stall #20',
    description:
      'A prime location for selling exotic goods from distant lands.',
    price: 235,
    purchased: false,
    id_prestataire: null,
    id_location_type: LocationType.PRESTATAIRE_LOCATION_TYPE_ID,
    position: [1734, 3571],
    icon_name: 'prestataire',
    banner_name: 'images/locations/buyable.png',
  },
  {
    id_location: 30,
    static_code: 'PRESTA_STALL_21',
    name: 'Merchant Stall #21',
    description:
      'Known for its vibrant colors and the enticing smell of delicious food.',
    price: 245,
    purchased: false,
    id_prestataire: null,
    id_location_type: LocationType.PRESTATAIRE_LOCATION_TYPE_ID,
    position: [1802, 1897],
    icon_name: 'prestataire',
    banner_name: 'images/locations/buyable.png',
  },
  {
    id_location: 31,
    static_code: 'PRESTA_STALL_22',
    name: 'Merchant Stall #22',
    description:
      'A popular spot for its variety of goods and friendly merchants.',
    price: 255,
    purchased: false,
    id_prestataire: null,
    id_location_type: LocationType.PRESTATAIRE_LOCATION_TYPE_ID,
    position: [1856, 1999],
    icon_name: 'prestataire',
    banner_name: 'images/locations/buyable.png',
  },
  {
    id_location: 32,
    static_code: 'PRESTA_STALL_23',
    name: 'Merchant Stall #23',
    description:
      'Close to the blacksmith, attracting customers looking for weapons and armor.',
    price: 265,
    purchased: false,
    id_prestataire: null,
    id_location_type: LocationType.PRESTATAIRE_LOCATION_TYPE_ID,
    position: [1914, 2113],
    icon_name: 'prestataire',
    banner_name: 'images/locations/buyable.png',
  },
  {
    id_location: 33,
    static_code: 'PRESTA_STALL_24',
    name: 'Merchant Stall #24',
    description: 'A favored location for its shade and the nearby well.',
    price: 275,
    purchased: false,
    id_prestataire: null,
    id_location_type: LocationType.PRESTATAIRE_LOCATION_TYPE_ID,
    position: [1694, 2113],
    icon_name: 'prestataire',
    banner_name: 'images/locations/buyable.png',
  },
  {
    id_location: 34,
    static_code: 'PRESTA_STALL_25',
    name: 'Merchant Stall #25',
    description:
      'Known for its strategic location near the guard post, ensuring safety and visibility.',
    price: 285,
    purchased: false,
    id_prestataire: null,
    id_location_type: LocationType.PRESTATAIRE_LOCATION_TYPE_ID,
    position: [1756, 2219],
    icon_name: 'prestataire',
    banner_name: 'images/locations/buyable.png',
  },
  {
    id_location: 35,
    static_code: 'PRESTA_STALL_26',
    name: 'Merchant Stall #26',
    description:
      'A prime spot for selling magical artifacts and rare ingredients.',
    price: 295,
    purchased: false,
    id_prestataire: null,
    id_location_type: LocationType.PRESTATAIRE_LOCATION_TYPE_ID,
    position: [1808, 2333],
    icon_name: 'prestataire',
    banner_name: 'images/locations/buyable.png',
  },
  {
    id_location: 37,
    static_code: 'PRESTA_STALL_28',
    name: 'Merchant Stall #28',
    description:
      'A cozy stall, ideal for selling baked goods and sweet treats.',
    price: 315,
    purchased: false,
    id_prestataire: null,
    id_location_type: LocationType.PRESTATAIRE_LOCATION_TYPE_ID,
    position: [1088, 1679],
    icon_name: 'prestataire',
    banner_name: 'images/locations/buyable.png',
  },
  {
    id_location: 38,
    static_code: 'PRESTA_STALL_29',
    name: 'Merchant Stall #29',
    description:
      'Known for its excellent view of the market square, ideal for attracting attention.',
    price: 325,
    purchased: false,
    id_prestataire: null,
    id_location_type: LocationType.PRESTATAIRE_LOCATION_TYPE_ID,
    position: [1282, 1625],
    icon_name: 'prestataire',
    banner_name: 'images/locations/buyable.png',
  },
  {
    id_location: 39,
    static_code: 'PRESTA_STALL_30',
    name: 'Merchant Stall #30',
    description:
      'A strategic location near the fountain, popular with both locals and tourists.',
    price: 335,
    purchased: false,
    id_prestataire: null,
    id_location_type: LocationType.PRESTATAIRE_LOCATION_TYPE_ID,
    position: [1394, 2167],
    icon_name: 'prestataire',
    banner_name: 'images/locations/buyable.png',
  },
  {
    id_location: 40,
    static_code: 'PRESTA_STALL_31',
    name: 'Merchant Stall #31',
    description:
      'Close to the entrance of the market, ensuring high visibility for your goods.',
    price: 345,
    purchased: false,
    id_prestataire: null,
    id_location_type: LocationType.PRESTATAIRE_LOCATION_TYPE_ID,
    position: [1086, 2329],
    icon_name: 'prestataire',
    banner_name: 'images/locations/buyable.png',
  },

  // === Toilet Locations  ===
  {
    id_location: 47,
    static_code: 'TOILET_1',
    name: 'Toilet #1',
    description:
      'A toilet located near the marketplace for public convenience.',
    price: 0,
    purchased: true,
    id_location_type: LocationType.OTHER_LOCATION_TYPE_ID,
    position: [1760, 2860],
    icon_name: 'toilet',
    banner_name: 'images/medieval_image.jpg',
  },
  {
    id_location: 48,
    static_code: 'TOILET_2',
    name: 'Toilet #2',
    description:
      'A toilet located near the marketplace for public convenience.',
    price: 0,
    purchased: true,
    id_location_type: LocationType.OTHER_LOCATION_TYPE_ID,
    position: [1010, 1832],
    icon_name: 'toilet',
    banner_name: 'images/medieval_image.jpg',
  },
  {
    id_location: 49,
    static_code: 'TOILET_3',
    name: 'Toilet #3',
    description:
      'A toilet located near the marketplace for public convenience.',
    price: 0,
    purchased: true,
    id_location_type: LocationType.OTHER_LOCATION_TYPE_ID,
    position: [3200, 3288],
    icon_name: 'toilet',
    banner_name: 'images/medieval_image.jpg',
  },
  {
    id_location: 50,
    static_code: 'TOILET_4',
    name: 'Toilet #4',
    description:
      'A toilet located near the marketplace for public convenience.',
    price: 0,
    purchased: true,
    id_location_type: LocationType.OTHER_LOCATION_TYPE_ID,
    position: [2142, 1184],
    icon_name: 'toilet',
    banner_name: 'images/medieval_image.jpg',
  },
  {
    id_location: 51,
    static_code: 'TOILET_5',
    name: 'Toilet #5',
    description:
      'A toilet located near the marketplace for public convenience.',
    price: 0,
    purchased: true,
    id_location_type: LocationType.OTHER_LOCATION_TYPE_ID,
    position: [1820, 3348],
    icon_name: 'toilet',
    banner_name: 'images/medieval_image.jpg',
  },
];

export async function seedLocations() {
  console.log('🌍 Seeding locations...');

  for (const location of LOCATION_SEEDS) {
    await prisma.location.upsert({
      where: { id_location: location.id_location },
      update: {
        name: location.name,
        description: location.description,
        static_code: location.static_code,
        price: location.price,
        purchased: location.purchased,
        position: location.position,
        icon_name: location.icon_name,
        banner_name: location.banner_name,
        id_location_type: location.id_location_type,
        id_prestataire: location.id_prestataire,
      },
      create: {
        id_location: location.id_location,
        name: location.name,
        description: location.description,
        static_code: location.static_code,
        price: location.price,
        purchased: location.purchased,
        position: location.position,
        icon_name: location.icon_name,
        banner_name: location.banner_name,
        id_location_type: location.id_location_type,
        id_prestataire: location.id_prestataire,
      },
    });
  }

  console.log('✅ Locations seeded');
}
