import prisma from '../prisma.js';
import bcrypt from 'bcrypt';
import { Role, AvatarType } from '@prisma/client';

export async function seedUsers() {
    const commonPassword = await bcrypt.hash('password123', 10);

    const users = [
        {
            id_user: 1,
            firstname: 'Gérard',
            lastname: 'Le prestataire',
            email: 'prestataire@medieval.com',
            password_hashed: commonPassword,
            role: 'prestataire' as Role,
            avatar_url: '/images/Avatar-images/con15.png',
            avatar_type: AvatarType.gallery,
            is_verified: false,
            xp: 250,
            level: 5,
            gold: 750,
            birth_date: new Date('1990-01-01'),
            bio: 'Je suis un prestataire',
            phone: '06 01 02 03 04',
            id_prestataire_type: 1
        },
        {
            id_user: 2,
            firstname: 'Alice',
            lastname: "L'Aventurière",
            email: 'aventurier@medieval.com',
            password_hashed: commonPassword,
            role: 'aventurier' as Role,
            avatar_url: '/images/Avatar-images/con23.png',
            avatar_type: AvatarType.gallery,
            is_verified: false,
            xp: 80,
            level: 2,
            gold: 150,
            birth_date: new Date('1992-01-01'),
            bio: 'Je suis une aventurière',
            phone: '06 02 03 04 05',
        },
        {
            id_user: 3,
            firstname: 'Godefroy',
            lastname: 'Le Sénéchal',
            email: 'admin@medieval.com',
            password_hashed: commonPassword,
            role: 'admin' as Role,
            avatar_url: '/images/Avatar-images/con1.png',
            avatar_type: AvatarType.gallery,
            is_verified: false,
            xp: 9999,
            level: 99,
            gold: 99999,
            birth_date: new Date('1980-01-01'),
            bio: 'Je suis le Sénéchal, responsable de la sécurité du royaume',
            phone: '06 03 04 05 06',
        },
        {
            id_user: 4,
            firstname: 'Marie',
            lastname: 'La marchande',
            email: 'prestataire2@medieval.com',
            password_hashed: commonPassword,
            role: 'prestataire' as Role,
            id_prestataire_type: 1,
            avatar_url: '/images/Avatar-images/con23.png',
            avatar_type: AvatarType.gallery,
            is_verified: false,
            xp: 150,
            level: 3,
            gold: 500,
        },
        {
            id_user: 5,
            firstname: 'Pierre',
            lastname: 'Le Paysan',
            email: 'pierre@medieval.com',
            password_hashed: commonPassword,
            role: 'aventurier' as Role,
            avatar_url: '/images/Avatar-images/con15.png',
            avatar_type: AvatarType.gallery,
            is_verified: false,
            xp: 20,
            level: 1,
            gold: 50,
            birth_date: new Date('1995-05-15'),
            bio: 'Juste un paysan qui veut aider.',
            phone: '06 05 06 07 08',
        },
        {
            id_user: 6,
            firstname: 'Jacques',
            lastname: 'L\'explorateur',
            email: 'jacques@medieval.com',
            password_hashed: commonPassword,
            role: 'aventurier' as Role,
            avatar_url: '/images/Avatar-images/con10.png',
            avatar_type: AvatarType.gallery,
            is_verified: false,
            xp: 180,
            level: 4,
            gold: 600,
            birth_date: new Date('1985-03-20'),
            bio: 'Explorateur depuis 20 ans.',
            phone: '06 05 06 07 08',
        },
        // Additional adventurers for quiz testing
        {
            id_user: 7,
            firstname: 'Thomas',
            lastname: 'Le Brave',
            email: 'thomas@medieval.com',
            password_hashed: commonPassword,
            role: 'aventurier' as Role,
            avatar_url: '/images/Avatar-images/con5.png',
            avatar_type: AvatarType.gallery,
            is_verified: false,
            xp: 450,
            level: 8,
            gold: 1200,
            birth_date: new Date('1998-02-14'),
            bio: 'Aventurier expérimenté en quête de gloire.',
            phone: '06 07 08 09 10',
        },
        {
            id_user: 8,
            firstname: 'Jeanne',
            lastname: 'La Courageuse',
            email: 'jeanne@medieval.com',
            password_hashed: commonPassword,
            role: 'aventurier' as Role,
            avatar_url: '/images/Avatar-images/con22.png',
            avatar_type: AvatarType.gallery,
            is_verified: false,
            xp: 320,
            level: 6,
            gold: 800,
            birth_date: new Date('1999-08-22'),
            bio: 'Passionnée d\'histoire médiévale.',
            phone: '06 08 09 10 11',
        },
        {
            id_user: 9,
            firstname: 'Léon',
            lastname: 'Le Curieux',
            email: 'leon@medieval.com',
            password_hashed: commonPassword,
            role: 'aventurier' as Role,
            avatar_url: '/images/Avatar-images/con8.png',
            avatar_type: AvatarType.gallery,
            is_verified: false,
            xp: 180,
            level: 4,
            gold: 450,
            birth_date: new Date('2001-11-05'),
            bio: 'Toujours prêt à apprendre.',
            phone: '06 09 10 11 12',
        },
        {
            id_user: 10,
            firstname: 'Margot',
            lastname: 'L\'Exploratrice',
            email: 'margot@medieval.com',
            password_hashed: commonPassword,
            role: 'aventurier' as Role,
            avatar_url: '/images/Avatar-images/con24.png',
            avatar_type: AvatarType.gallery,
            is_verified: false,
            xp: 520,
            level: 9,
            gold: 1500,
            birth_date: new Date('1997-04-18'),
            bio: 'Exploratrice des terres médiévales.',
            phone: '06 10 11 12 13',
        },
    ];

    console.log('Seeding users...');

    for (const user of users) {
        // Determine default id_prestataire_type if needed for non-prestataires to avoid constraint errors
        // Assuming schema allows it to be arbitrary if not relationally enforced for non-prestataires, 
        // or we set it to 1 (default) if required.
        // Based on previous simple seed, we defaulted it to 1.
        const prestataireTypeId = user.id_prestataire_type || 1;

        await prisma.user.upsert({
            where: { email: user.email },
            update: {
                firstname: user.firstname,
                lastname: user.lastname,
                role: user.role,
                avatar_url: user.avatar_url,
                avatar_type: user.avatar_type,
                xp: user.xp,
                level: user.level,
                gold: user.gold,
                birth_date: user.birth_date,
                bio: user.bio,
                phone: user.phone,
                id_prestataire_type: prestataireTypeId,
                password_hashed: commonPassword, // Ensure password matches mocks
            },
            create: {
                firstname: user.firstname,
                lastname: user.lastname,
                email: user.email,
                password_hashed: commonPassword,
                role: user.role,
                avatar_url: user.avatar_url,
                avatar_type: user.avatar_type,
                level: user.level,
                xp: user.xp,
                gold: user.gold,
                is_verified: user.is_verified,
                birth_date: user.birth_date,
                bio: user.bio,
                phone: user.phone,
                id_prestataire_type: prestataireTypeId,
            },
        });
    }

    console.log('Users seeded');
}
