name: Deploy to Oracle Cloud

on:
  push:
    branches:
      - main   # or master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: oracle-cloud   # this makes it show up in the "Environments" tab
      url: http://minecraft.constantsuchet.fr   # link that appears in the deployment status
    steps:
      # 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Setup Node
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      # 3. Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4. Run frontend tests
      - name: Run frontend tests
        run: npx nx test @sae-project-but2/frontend

      # 5. Build frontend in "nobackend" mode
      - name: Build frontend (nobackend)
        run: npx nx build @sae-project-but2/frontend --mode=nobackend

      # 6. Verify build output
      - name: Check build output
        run: |
          echo "Checking build output..."
          ls -la frontend/dist/
          echo "Build output contents:"
          find frontend/dist/ -type f | head -10

      # 7. Setup SSH key
      - name: Setup SSH key
        if: success()
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.ORACLE_SSH_KEY }}" > ~/.ssh/oracle_key
          chmod 600 ~/.ssh/oracle_key
          ssh-keyscan -H ${{ secrets.ORACLE_HOST }} >> ~/.ssh/known_hosts

      # 8. Fix permissions on server
      - name: Fix server permissions
        if: success()
        run: |
          ssh -i ~/.ssh/oracle_key -o StrictHostKeyChecking=no ${{ secrets.ORALCE_USER }}@${{ secrets.ORACLE_HOST }} "sudo chown -R ${{ secrets.ORALCE_USER }}:${{ secrets.ORALCE_USER }} /var/www/html && sudo chmod -R 755 /var/www/html"

      # 9. Deploy to Oracle Cloud
      - name: Deploy to Oracle Cloud
        if: success()   # only deploy if tests + build succeed
        run: |
          echo "Uploading build files to Oracle Cloud..."
          scp -i ~/.ssh/oracle_key -o StrictHostKeyChecking=no -r frontend/dist/* ${{ secrets.ORALCE_USER }}@${{ secrets.ORACLE_HOST }}:/var/www/html/

      # 10. Restart Nginx
      - name: Restart Nginx
        if: success()
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.ORACLE_HOST }}
          username: ${{ secrets.ORALCE_USER }}
          key: ${{ secrets.ORACLE_SSH_KEY }}
          script: sudo systemctl restart nginx